### ISSUE TITLE
Dependency installation

### ISSUE THREAD

**Issue by Lansorian** [akshaybahadur21/QuickDraw#17]
In the readme.md, when you say
**`pip install requirements.txt`**
I suppose you mean
**`pip install -r requirements.txt`**?

Also in the requirements.txt,
I think **`cv2`** should be replaced by **`opencv-python`**

At least on my side doing so resolve the erros; if this is not a typo/bug but a version/enviornment thing,
please tell me more about it. Thanks.

**Comment by akshaybahadur21** [comment]
@Lansorian  - Thanks for pointing it out.
Making the changes
