### ISSUE TITLE
Error in QuickDrawApp.py

### ISSUE THREAD

**Issue by aakarshachug19** [akshaybahadur21/QuickDraw#4]
Hi akshay, your work is amazing! 
I am facing this type error in quickdrawapp.py and the code gets terminated after that. Hope you can help!

Traceback (most recent call last):
  File "QuickDrawApp.py", line 131, in <module>
    main()
  File "QuickDrawApp.py", line 55, in main
    if len(blackboard_cnts) >= 1:
TypeError: object of type 'NoneType' has no len()
[ WARN:0] terminating async callback

**Comment by VikasChowdary** [comment]
Hey Akshay,I'm also getting the same termination error as  ::
 
Traceback (most recent call last):
File "QuickDrawApp.py", line 131, in 
main()
File "QuickDrawApp.py", line 55, in main
if len(blackboard_cnts) >= 1:
TypeError: object of type 'NoneType' has no len()
[ WARN:0] terminating async callback

Please resolve this.

**Comment by VikasChowdary** [comment]
I tried measuring the list.__len__() instead of len()  and it worked fine.

**Comment by Aakarsha19chugh** [comment]
> Hey Akshay,I'm also getting the same termination error as ::
> 
> Traceback (most recent call last):
> File "QuickDrawApp.py", line 131, in
> main()
> File "QuickDrawApp.py", line 55, in main
> if len(blackboard_cnts) >= 1:
> TypeError: object of type 'NoneType' has no len()
> [ WARN:0] terminating async callback
> 
> Please resolve this.
