### ISSUE TITLE
Not predicting perfectly when passing a drawn image as input.

### ISSUE THREAD

**Issue by vinic15** [akshaybahadur21/QuickDraw#7]
I have modified your script in such a way that it takes a drawn sketch as input and predict it.but unfortunately it is making completely wrong predictions.what should i do? I have used your model as well as my self trained model both are not working.

**Comment by akshaybahadur21** [comment]
@vinic15 - I think you need to train a better model.
I have only used 15 categories from a list of all the categories provided by Quick, Draw.
