### ISSUE TITLE
Doubt in code

### ISSUE THREAD

**Issue by abhichacko** [akshaybahadur21/QuickDraw#8]
i did not understand the use of the following code in the file LoadData.py

features=features.reshape(features.shape[0]*features.shape[1],features.shape[2])
labels=labels.reshape(labels.shape[0]*labels.shape[1],labels.shape[2])

can you please explain this two lines of code plz?

**Comment by akshaybahadur21** [comment]
@abhichacko - I am reshaping the features and labels by multiplying first and second dimension. This is then stored in pickle file
